[package]
name = "rusty_check_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"]}
proc-macro2 = "1.0"
mockall = "0.13.1"
