repos:
- repo: https://github.com/jkszymczak/pre-commit-hooks
  rev: v0.0.2
  hooks:
      - id: run-command
        args: [rustfmt]
        files: \.rs$
        verbose: true

- repo: https://github.com/jkszymczak/pre-commit-hooks
  rev: v0.0.1
  hooks:
      - id: run-command
        args: [plantuml,-tsvg, -r .]
        files: \.puml$
        verbose: true
