[package]
name = "rusty_check"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits","visit"]}
proc-macro2 = "1.0"