<rusty_check> ::= <cases> | " "
<cases> ::= <case> <cases> | <case>
<case> ::= "case " <identifier> "{ " <given> <check> " }"
<given> ::= "given" "{ " <assignments> " }" | " "
<assignments> ::= <assignment> "," <assignments>
                | <assignment>
                | " "
<assignment> ::= <identifier> " = " <expression>
<compute> ::=  "do" "{" <rust_code> "}"
<check> ::= "check" "{ " <conditions> " }"
<conditions> ::= <condition> " or " <conditions>
               | <condition> " and " <conditions>
               | "for any " <identifier> " in " <identifier> ", " <conditions>
               | "for each " <identifier> " in " <identifier> ", " <conditions>
               | <condition>
<condition> ::= <expression> <symbol> <expression>
<symbol> ::= " equal "
           | <other_symbol>
           | " equal or " <other_symbol>
<other_symbol> ::= " less than "
                 | " greater than "
<expression> ::=  <rust_expression>
                | <rust_block>
<rust_block> ::= " rust {" <rust_code> "}"
<rust_code> ::= " "
<rust_expression> ::= " "
<identifier> ::= ( [a-z] | [A-Z] ) ( [a-z] | [A-Z] )+"
