@startebnf
!theme hacker
skinparam backgroundColor white
rusty_check = {case | rust_code};
global = "global", "{", global_assignments ,"}";
global_assignments = [global_constants], [global_variables] | [global_variables], [global_constants];
global_variables = ["variables", "{", [assignments], "}"]; 
global_constants = ["const", "{", [non_mutable_assignments], "}"];
non_mutable_assignments = non_mutable_assignment, {",", non_mutable_assignment};

case = "case", identifier, "{", [given], [compute], check, "}";

given = "given", "{", assignments, "}";
assignments = {assignment};
assignment = non_mutable_assignment 
            | mutable_assignment;
non_mutable_assignment = identifier, "=", expression;
mutable_assignment = "mut", non_mutable_assignment;
compute = "do", "{", rust_code, "}";
create_mock = " ";
compose_mock = "compose mocks of", {identifier}-, "into", identifier;

check = "check", "{", conditions, "}";
conditions = condition, ("or" | "and" ), conditions
             | "for", ("any"|"each"), identifier, "in", identifier, ",", conditions
             | condition;
condition = expression, symbol, expression;
symbol = "equal"
         | other_symbol
         | "equal or", other_symbol;
other_symbol = "less than"
               | "greater than";

expression = rust_expression 
             | rust_block;
rust_block = "rust", "{", rust_code, "}";
rust_code = "any valid rust code";
rust_expression = "any rust expression";
identifier = {? a-z ? | ? A-Z ?}-, {(? a-z ? | ? A-Z ? | ? 0-9 ?)};
@endebnf