@startebnf
!define MAIN_RENDER
rusty_check = [global], {case | rust_code};
!include global/global.puml
!include case/case.puml
!include assignment.puml
create_mock = " ";
compose_mock = "compose mocks of", {identifier}-, "into", identifier;

expression = rust_expression 
             | rust_block;
rust_block = "rust", "{", rust_code, "}";
rust_code = "any valid rust code";
rust_expression = "any rust expression";
identifier = "any valid identifier";
@endebnf